name: Smashcut
options:
  bundleIdPrefix: com.nh273
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: ""  # Set your team in Xcode: Smashcut target → Signing & Capabilities

targets:
  Smashcut:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Smashcut
    info:
      path: Smashcut/Info.plist
      properties:
        NSCameraUsageDescription: "Smashcut needs camera access to record your narration."
        NSMicrophoneUsageDescription: "Smashcut needs microphone access to record your voice."
        NSPhotoLibraryUsageDescription: "Smashcut needs photo library access to pick background media."
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        ITSAppUsesNonExemptEncryption: false
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.nh273.smashcut
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_FILE: Smashcut/Info.plist
    dependencies:
      - sdk: AVFoundation.framework
      - sdk: Vision.framework
      - sdk: Photos.framework
      - sdk: CoreImage.framework

  SmashcutTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: SmashcutTests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.nh273.smashcut.tests
    dependencies:
      - target: Smashcut
